TESS Sectors Numbers for ```nearby_TOI_MDs.csv```

In [1]:
from toi_catalog import load_catalog, get_target_by_tic, process_first_sector_targets
import pandas as pd

manually selecting ```tic_id``` for this example

In [2]:
code_path = "/Users/madelinejmg/Desktop/PHYS39002/research2026/Catalog/nearby_TOI_MDs.csv"
df = load_catalog(code_path)

In [3]:
tic_id = 410153553
# checking how many sectors per target
params = get_target_by_tic(df, tic_id=tic_id, sector = None)
params

,tic_id,sectors,n_sectors,pipelines,P_days,T0,depth_frac,duration_hr
0,410153553,"1,27,28,67,68,94,95,101,102,103,104",11,[SPOC],0.462931,1325.724661,0.004678,0.631015

Grab the first number (the first LC per target star) for now

In [4]:
# grab the sectors string from the first matching row
sectors_str = df.loc[df["TIC ID"] == tic_id, "Sectors"].iloc[0]

# parse it into ints
sectors = [int(float(s.strip())) for s in str(sectors_str).split(",") if s.strip()]
print(f'TIC ID {tic_id}: Sector(s) {sectors}')

TIC ID 410153553: Sector(s) [1, 27, 28, 67, 68, 94, 95, 101, 102, 103, 104]

In [5]:
print(f'First number of TIC ID {tic_id}: Sector {sectors[0]}')

First number of TIC ID 410153553: Sector 1

----

getting first sectors all TIC's

In [6]:
results = process_first_sector_targets(df)

TIC ID 410153553: First sector 1
TIC ID 234994474: First sector 1
TIC ID 206609630: First sector 1
TIC ID 231702397: First sector 1
TIC ID 234523599: First sector 1
TIC ID 299798795: First sector 1
TIC ID 394357918: First sector 1
TIC ID 12421862: First sector 2
TIC ID 262530407: First sector 2
TIC ID 307210830: First sector 2
TIC ID 141527579: First sector 1
TIC ID 32090583: First sector 1
TIC ID 55650590: First sector 1
TIC ID 237914496: First sector 1
TIC ID 305048087: First sector 2
TIC ID 260004324: First sector 1
TIC ID 118327550: First sector 2
TIC ID 12423815: First sector 2
TIC ID 415969908: First sector 2
TIC ID 120916706: First sector 3
TIC ID 150428135: First sector 1
TIC ID 415969908: First sector 2
TIC ID 153065527: First sector 3
TIC ID 220479565: First sector 3
TIC ID 259377017: First sector 3
TIC ID 259377017: First sector 3
TIC ID 259377017: First sector 3
TIC ID 92226327: First sector 3
TIC ID 439456714: First sector 3
TIC ID 244161191: First sector 3
TIC ID 98796344: First sector 4
TIC ID 153077621: First sector 3
TIC ID 29960110: First sector 4
TIC ID 44737596: First sector 4
TIC ID 77156829: First sector 4
TIC ID 89256802: First sector 4
TIC ID 77951245: First sector 5
TIC ID 52280468: First sector 6
TIC ID 33521996: First sector 6
TIC ID 55488511: First sector 5
TIC ID 53593457: First sector 6
TIC ID 200593988: First sector 6
TIC ID 202185707: First sector 6
TIC ID 32830028: First sector 6
TIC ID 237751146: First sector 6
TIC ID 192826603: First sector 5
TIC ID 302895996: First sector 6
TIC ID 452866790: First sector 7
TIC ID 387690507: First sector 6
TIC ID 438490744: First sector 6
TIC ID 218795833: First sector 7
TIC ID 348538431: First sector 7
TIC ID 431999925: First sector 7
TIC ID 27649847: First sector 7
TIC ID 296739893: First sector 8
TIC ID 296780789: First sector 8
TIC ID 82362447: First sector 8
TIC ID 146463781: First sector 7
TIC ID 413248763: First sector 8
TIC ID 119081096: First sector 8
TIC ID 150428135: First sector 1
TIC ID 158588995: First sector 9
TIC ID 54962195: First sector 9
TIC ID 151825527: First sector 9
TIC ID 35009898: First sector 9
TIC ID 54962195: First sector 9
TIC ID 447061717: First sector 9
TIC ID 101955023: First sector 9
TIC ID 219195044: First sector 1
TIC ID 237920046: First sector 1
TIC ID 271971130: First sector 1
TIC ID 149788158: First sector 8
TIC ID 231728511: First sector 4
TIC ID 77156829: First sector 4
TIC ID 271596225: First sector 1
TIC ID 150428135: First sector 1
TIC ID 34068865: First sector 9
TIC ID 36724087: First sector 9
TIC ID 181804752: First sector 9
TIC ID 181804752: First sector 9
TIC ID 36724087: First sector 9
TIC ID 359271092: First sector 9
TIC ID 219195044: First sector 1
TIC ID 271596225: First sector 1
TIC ID 300710077: First sector 1
TIC ID 374829238: First sector 2
TIC ID 38460940: First sector 1
TIC ID 5868998: First sector 10
TIC ID 178709444: First sector 10
TIC ID 429358906: First sector 10
TIC ID 306996324: First sector 10
TIC ID 306996324: First sector 10
TIC ID 92226327: First sector 3
TIC ID 260708537: First sector 1
TIC ID 73649615: First sector 10
TIC ID 200322593: First sector 4
TIC ID 432008938: First sector 7
TIC ID 307210830: First sector 2
TIC ID 141608198: First sector 1
TIC ID 307210830: First sector 2
TIC ID 277634430: First sector 10
TIC ID 125405602: First sector 11
TIC ID 166184426: First sector 11
TIC ID 261257684: First sector 12
TIC ID 248250955: First sector 12
TIC ID 369327947: First sector 12
TIC ID 406941612: First sector 12
TIC ID 70797900: First sector 2
TIC ID 90504905: First sector 14
TIC ID 219698776: First sector 14
TIC ID 229781583: First sector 14
TIC ID 274762761: First sector 14
TIC ID 467179528: First sector 14
TIC ID 163539739: First sector 15
TIC ID 267561446: First sector 15
TIC ID 274662200: First sector 15
TIC ID 408203470: First sector 14
TIC ID 453260209: First sector 10
TIC ID 360156606: First sector 11
TIC ID 370133522: First sector 13
TIC ID 161032923: First sector 13
TIC ID 351601843: First sector 13
TIC ID 322270620: First sector 12
TIC ID 300710077: First sector 1
TIC ID 300710077: First sector 1
TIC ID 467179528: First sector 14
TIC ID 13684720: First sector 14
TIC ID 235683377: First sector 14
TIC ID 259168516: First sector 14
TIC ID 377293776: First sector 14
TIC ID 343628284: First sector 15
TIC ID 420112589: First sector 14
TIC ID 284441182: First sector 17
TIC ID 427654774: First sector 17
TIC ID 240968774: First sector 17
TIC ID 243185500: First sector 17
TIC ID 243185500: First sector 17
TIC ID 424747720: First sector 13
TIC ID 201186294: First sector 18
TIC ID 51024887: First sector 18
TIC ID 396562848: First sector 18
TIC ID 28900646: First sector 19
TIC ID 470381900: First sector 19
TIC ID 353475866: First sector 19
TIC ID 422756130: First sector 18
TIC ID 81212286: First sector 20
TIC ID 318022259: First sector 20
TIC ID 318022259: First sector 20
TIC ID 232635922: First sector 14
TIC ID 219860288: First sector 15
TIC ID 232650365: First sector 14
TIC ID 233602827: First sector 14
TIC ID 233602827: First sector 14
TIC ID 287139872: First sector 14
TIC ID 332477926: First sector 14
TIC ID 364074068: First sector 17
TIC ID 420112587: First sector 14
TIC ID 441739871: First sector 14
TIC ID 67646988: First sector 21
TIC ID 348755728: First sector 8
TIC ID 359357695: First sector 11
TIC ID 119584412: First sector 22
TIC ID 138762614: First sector 22
TIC ID 166648874: First sector 22
TIC ID 138819293: First sector 22
TIC ID 390651552: First sector 23
TIC ID 198385543: First sector 17
TIC ID 236387002: First sector 24
TIC ID 142748283: First sector 14
TIC ID 142748283: First sector 14
TIC ID 224298134: First sector 15
TIC ID 198485881: First sector 14
TIC ID 321669174: First sector 14
TIC ID 235678745: First sector 14
TIC ID 356016119: First sector 14
TIC ID 235678745: First sector 14
TIC ID 417931300: First sector 14
TIC ID 356871098: First sector 14
TIC ID 441738827: First sector 15
TIC ID 441738827: First sector 15
TIC ID 188589164: First sector 24
TIC ID 368287008: First sector 24
TIC ID 405763009: First sector 14
TIC ID 389900760: First sector 18
TIC ID 44313455: First sector 26
TIC ID 336128819: First sector 26
TIC ID 287139872: First sector 14
TIC ID 8348911: First sector 24
TIC ID 71347873: First sector 20
TIC ID 243313296: First sector 14
TIC ID 236934937: First sector 15
TIC ID 441798995: First sector 14
TIC ID 329148988: First sector 16
TIC ID 321688498: First sector 17
TIC ID 38680052: First sector 1
TIC ID 459837008: First sector 19
TIC ID 441798995: First sector 14
TIC ID 168751223: First sector 4
TIC ID 212957629: First sector 3
TIC ID 29959760: First sector 4
TIC ID 153078576: First sector 3
TIC ID 219175972: First sector 1
TIC ID 439867639: First sector 4
TIC ID 4294779: First sector 6
TIC ID 170789802: First sector 5
TIC ID 59128183: First sector 5
TIC ID 434260570: First sector 5
TIC ID 33091590: First sector 7
TIC ID 160328683: First sector 6
TIC ID 261135533: First sector 15
TIC ID 146776480: First sector 8
TIC ID 176772671: First sector 8
TIC ID 135036669: First sector 9
TIC ID 302527524: First sector 9
TIC ID 243641947: First sector 11
TIC ID 165827520: First sector 11
TIC ID 305478010: First sector 15
TIC ID 155867025: First sector 19
TIC ID 458419328: First sector 20
TIC ID 86263325: First sector 22
TIC ID 20182780: First sector 23
TIC ID 141616639: First sector 19
TIC ID 434105094: First sector 2
TIC ID 219175972: First sector 1
TIC ID 271596225: First sector 1
TIC ID 77156829: First sector 4
TIC ID 54962195: First sector 9
TIC ID 153065527: First sector 3
TIC ID 149788158: First sector 8
TIC ID 44898913: First sector 4
TIC ID 176797879: First sector 4
TIC ID 62301521: First sector 13
TIC ID 354944123: First sector 13
TIC ID 354944123: First sector 13
TIC ID 313889049: First sector 2
TIC ID 408416746: First sector 8
TIC ID 4070275: First sector 5
TIC ID 52307802: First sector 1
TIC ID 271169413: First sector 11
TIC ID 140687214: First sector 1
TIC ID 166184428: First sector 11
TIC ID 22233480: First sector 40
TIC ID 230129753: First sector 14
TIC ID 348054109: First sector 26
TIC ID 193336820: First sector 14
TIC ID 239332587: First sector 15
TIC ID 126606859: First sector 15
TIC ID 12938488: First sector 41
TIC ID 39926974: First sector 42
TIC ID 380887434: First sector 42
TIC ID 384888319: First sector 42
TIC ID 261257684: First sector 12
TIC ID 150428135: First sector 1
TIC ID 381897917: First sector 13
TIC ID 149126400: First sector 1
TIC ID 107018378: First sector 10
TIC ID 298428237: First sector 14
TIC ID 103605399: First sector 14
TIC ID 154940895: First sector 19
TIC ID 137683938: First sector 14
TIC ID 307809773: First sector 43
TIC ID 286201103: First sector 15
TIC ID 307809773: First sector 43
TIC ID 232650365: First sector 14
TIC ID 459837008: First sector 19
TIC ID 224298134: First sector 15
TIC ID 258796169: First sector 17
TIC ID 94727308: First sector 43
TIC ID 336961891: First sector 42
TIC ID 270355392: First sector 4
TIC ID 203214081: First sector 44
TIC ID 19028197: First sector 44
TIC ID 150096001: First sector 43
TIC ID 184892124: First sector 44
TIC ID 434226736: First sector 44
TIC ID 142938659: First sector 4
TIC ID 165202476: First sector 31
TIC ID 404506270: First sector 4
TIC ID 60074373: First sector 7
TIC ID 143032776: First sector 36
TIC ID 335590096: First sector 10
TIC ID 262499797: First sector 3
TIC ID 324609476: First sector 27
TIC ID 318180448: First sector 13
TIC ID 203289099: First sector 44
TIC ID 213111428: First sector 12
TIC ID 173103335: First sector 45
TIC ID 277833995: First sector 8
TIC ID 95337971: First sector 45
TIC ID 437054764: First sector 44
TIC ID 318022259: First sector 20
TIC ID 264301607: First sector 14
TIC ID 147892178: First sector 14
TIC ID 419411415: First sector 15
TIC ID 4619242: First sector 42
TIC ID 246965431: First sector 18
TIC ID 33397739: First sector 42
TIC ID 250111245: First sector 42
TIC ID 202468443: First sector 15
TIC ID 126982221: First sector 42
TIC ID 16005254: First sector 43
TIC ID 26054627: First sector 42
TIC ID 90767677: First sector 18
TIC ID 407591297: First sector 21
TIC ID 171646471: First sector 22
TIC ID 39143128: First sector 22
TIC ID 56798909: First sector 44
TIC ID 443582629: First sector 9
TIC ID 389040826: First sector 8
TIC ID 377097547: First sector 45
TIC ID 291109653: First sector 23
TIC ID 270355392: First sector 4
TIC ID 468983280: First sector 7
TIC ID 443616612: First sector 9
TIC ID 443616612: First sector 9
TIC ID 244170332: First sector 3
TIC ID 345450130: First sector 5
TIC ID 458686847: First sector 34
TIC ID 87405719: First sector 45
TIC ID 387974148: First sector 43
TIC ID 330637910: First sector 44
TIC ID 388804061: First sector 45
TIC ID 323687123: First sector 44
TIC ID 237108775: First sector 14
TIC ID 252481136: First sector 21
TIC ID 160162137: First sector 14
TIC ID 252928337: First sector 20
TIC ID 141202786: First sector 22
TIC ID 119585136: First sector 22
TIC ID 459762279: First sector 20
TIC ID 23863105: First sector 16
TIC ID 198162530: First sector 14
TIC ID 310380289: First sector 16
TIC ID 157769780: First sector 14
TIC ID 219875976: First sector 14
TIC ID 298074836: First sector 14
TIC ID 230055368: First sector 22
TIC ID 103865797: First sector 25
TIC ID 147923561: First sector 14
TIC ID 4918918: First sector 21
TIC ID 219041246: First sector 16
TIC ID 286813592: First sector 22
TIC ID 138820713: First sector 22
TIC ID 166648874: First sector 22
TIC ID 166648874: First sector 22
TIC ID 193634953: First sector 25
TIC ID 120045750: First sector 14
TIC ID 289666986: First sector 19
TIC ID 72889156: First sector 25
TIC ID 328081248: First sector 54
TIC ID 264468702: First sector 18
TIC ID 354727907: First sector 14
TIC ID 434116397: First sector 56
TIC ID 354173595: First sector 42
TIC ID 296898634: First sector 15
TIC ID 305506996: First sector 55
TIC ID 329709756: First sector 15
TIC ID 236785891: First sector 14
TIC ID 14956304: First sector 14
TIC ID 258037656: First sector 55
TIC ID 353146308: First sector 55
TIC ID 380517859: First sector 15
TIC ID 259233660: First sector 14
TIC ID 102734241: First sector 14
TIC ID 279922257: First sector 18
TIC ID 446157122: First sector 19
TIC ID 48353358: First sector 14
TIC ID 339591840: First sector 53
TIC ID 18318288: First sector 25
TIC ID 233602827: First sector 14
TIC ID 198162530: First sector 14
TIC ID 7439480: First sector 11
TIC ID 388076422: First sector 16
TIC ID 455947620: First sector 16
TIC ID 435878153: First sector 17
TIC ID 459837008: First sector 19
TIC ID 455947620: First sector 16
TIC ID 52005579: First sector 42
TIC ID 321669174: First sector 14
TIC ID 44295981: First sector 56
TIC ID 404456775: First sector 56
TIC ID 86005116: First sector 55
TIC ID 288144647: First sector 57
TIC ID 352147273: First sector 17
TIC ID 286763141: First sector 9
TIC ID 85281192: First sector 17
TIC ID 186715217: First sector 18
TIC ID 308120029: First sector 18
TIC ID 372207328: First sector 16
TIC ID 16550540: First sector 60
TIC ID 328513434: First sector 19
TIC ID 459982699: First sector 14
TIC ID 122798633: First sector 7
TIC ID 168936945: First sector 7
TIC ID 274002141: First sector 19
TIC ID 259502942: First sector 19
TIC ID 166145361: First sector 11
TIC ID 332657786: First sector 8
TIC ID 184801054: First sector 34
TIC ID 376800517: First sector 10
TIC ID 445522339: First sector 7
TIC ID 47143972: First sector 8
TIC ID 45881495: First sector 9
TIC ID 356921678: First sector 9
TIC ID 382187347: First sector 1
TIC ID 142277868: First sector 10
TIC ID 22560356: First sector 10
TIC ID 144077896: First sector 10
TIC ID 148691985: First sector 38
TIC ID 160442729: First sector 11
TIC ID 349503728: First sector 12
TIC ID 167573692: First sector 1
TIC ID 418343229: First sector 19
TIC ID 112115898: First sector 7
TIC ID 261264800: First sector 1
TIC ID 34986694: First sector 9
TIC ID 269849065: First sector 1
TIC ID 443823169: First sector 7
TIC ID 303364023: First sector 9
TIC ID 299798795: First sector 1
TIC ID 32090583: First sector 1
TIC ID 262470965: First sector 67
TIC ID 349891396: First sector 13
TIC ID 383313006: First sector 13
TIC ID 291013124: First sector 27
TIC ID 261679541: First sector 1
TIC ID 344552721: First sector 13
TIC ID 230982415: First sector 2
TIC ID 201254754: First sector 1
TIC ID 281596890: First sector 2
TIC ID 28872266: First sector 42
TIC ID 83181153: First sector 43
TIC ID 63100069: First sector 71
TIC ID 67512645: First sector 22
TIC ID 421006834: First sector 7
TIC ID 337217173: First sector 4
TIC ID 468983280: First sector 7
TIC ID 57147191: First sector 44
TIC ID 11894726: First sector 22
TIC ID 219707850: First sector 14
TIC ID 446166017: First sector 22
TIC ID 22740615: First sector 22
TIC ID 364571121: First sector 15
TIC ID 376354189: First sector 18
TIC ID 272829240: First sector 17
TIC ID 459323923: First sector 25
TIC ID 288421619: First sector 82
TIC ID 341005781: First sector 15
TIC ID 277853911: First sector 15
TIC ID 268727719: First sector 17
TIC ID 77490011: First sector 18
TIC ID 258776466: First sector 14
TIC ID 198358065: First sector 14
TIC ID 18885659: First sector 80
TIC ID 160075684: First sector 14
TIC ID 282113152: First sector 55
TIC ID 161687285: First sector 15
TIC ID 219089784: First sector 15
TIC ID 275717567: First sector 15
TIC ID 83299322: First sector 14
TIC ID 161687211: First sector 15
TIC ID 73729607: First sector 58
TIC ID 154480367: First sector 16
TIC ID 374177909: First sector 16
TIC ID 374173310: First sector 16
TIC ID 73692250: First sector 18
TIC ID 233747840: First sector 14
TIC ID 251090642: First sector 21
TIC ID 192833836: First sector 5
TIC ID 76835246: First sector 92
TIC ID 111778581: First sector 2

In [7]:
len(results)

471

In [10]:
combined = pd.concat(results, ignore_index=True)
combined.head()

,tic_id,sectors,n_sectors,pipelines,P_days,T0,depth_frac,duration_hr
0,410153553,"1,27,28,67,68,94,95,101,102,103,104",11,[SPOC],0.462931,1325.724661,0.004678,0.631015
1,234994474,"1,28,68,95,102,104,105",7,[SPOC/QLP],1.401518,1326.034032,0.000594,1.158306
2,206609630,"1,2,28,29,68,69,95,96,104",9,[SPOC],0.335272,1325.490344,0.019688,0.718986
3,231702397,"1,27,28,67,68,95,102,103,104,105",10,[SPOC],5.078033,1329.118988,0.005923,1.210035
4,234523599,"1,2,28,29,68,69,95,96,103,104",10,[SPOC],3.795518,1325.650603,0.052279,2.019813

In [9]:
tic_id = 206609630
row = df[df["TIC ID"] == tic_id]
row.head()

,Parameter Source Pipeline,Detection Pipeline(s),TIC ID,Full TOI ID,TOI Disposition,TIC Right Ascension,TIC Declination,TIC Right Ascension 2015.5,TIC Declination 2015.5,TMag Value,...,M_planet [ME],K_RV [m/s],TSM,ESM,Stellar Insolation [ergs/cm^2/s],Stellar Insolation [Earth Units],Sectors_Observed,Cameras,CCDs,EdgeWarn
2,spoc-s01-s69-b0A-APC,SPOC,206609630,212.01,PC,22.551,-59.5832,22.550065,-59.583245,12.186,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,"3,3,3,3,3,3,3,3,3","1,2,1,2,1,2,1,2,3","0,0,0,0,0,0,0,0,0"