TESS Sectors Numbers for ```nearby_TOI_MDs.csv```

In [1]:
from toi_catalog import load_catalog, get_target_by_tic, process_first_sector_targets
import pandas as pd

manually selecting ```tic_id``` for this example

In [2]:
code_path = "/Users/madelinejmg/Desktop/PHYS39002/research2026/Catalog/nearby_TOI_MDs.csv"
df = load_catalog(code_path)

In [3]:
tic_id = 410153553
# checking how many sectors per target
params = get_target_by_tic(df, tic_id=tic_id, sector = None)
params

,tic_id,sectors,n_sectors,pipelines,P_days,T0,depth_frac,duration_hr
0,410153553,"1,27,28,67,68,94,95,101,102,103,104",11,[SPOC],0.462931,1325.724661,0.004678,0.631015

Grab the first number (the first LC per target star) for now

In [4]:
# grab the sectors string from the first matching row
sectors_str = df.loc[df["TIC ID"] == tic_id, "Sectors"].iloc[0]

# parse it into ints
sectors = [int(float(s.strip())) for s in str(sectors_str).split(",") if s.strip()]
print(f'TIC ID {tic_id}: Sector(s) {sectors}')

TIC ID 410153553: Sector(s) [1, 27, 28, 67, 68, 94, 95, 101, 102, 103, 104]

In [5]:
print(f'First number of TIC ID {tic_id}: Sector {sectors[0]}')

First number of TIC ID 410153553: Sector 1

----

getting first sectors all TIC's

In [ ]:
results = process_first_sector_targets(df)

TIC ID 410153553: First sector 1
TIC ID 234994474: First sector 1
TIC ID 206609630: First sector 1
TIC ID 231702397: First sector 1
TIC ID 234523599: First sector 1
TIC ID 299798795: First sector 1
TIC ID 394357918: First sector 1
TIC ID 12421862: First sector 2
TIC ID 262530407: First sector 2
TIC ID 307210830: First sector 2
TIC ID 141527579: First sector 1
TIC ID 32090583: First sector 1
TIC ID 55650590: First sector 1
TIC ID 237914496: First sector 1
TIC ID 305048087: First sector 2
TIC ID 260004324: First sector 1
TIC ID 118327550: First sector 2
TIC ID 12423815: First sector 2
TIC ID 415969908: First sector 2
TIC ID 120916706: First sector 3
TIC ID 150428135: First sector 1
TIC ID 415969908: First sector 2
TIC ID 153065527: First sector 3
TIC ID 220479565: First sector 3
TIC ID 259377017: First sector 3
TIC ID 259377017: First sector 3
TIC ID 259377017: First sector 3
TIC ID 92226327: First sector 3
TIC ID 439456714: First sector 3
TIC ID 244161191: First sector 3
TIC ID 98796344: First sector 4
TIC ID 153077621: First sector 3
TIC ID 29960110: First sector 4
TIC ID 44737596: First sector 4
TIC ID 77156829: First sector 4
TIC ID 89256802: First sector 4
TIC ID 77951245: First sector 5
TIC ID 52280468: First sector 6
TIC ID 33521996: First sector 6
TIC ID 55488511: First sector 5
TIC ID 53593457: First sector 6
TIC ID 200593988: First sector 6
TIC ID 202185707: First sector 6
TIC ID 32830028: First sector 6
TIC ID 237751146: First sector 6
TIC ID 192826603: First sector 5
TIC ID 302895996: First sector 6
TIC ID 452866790: First sector 7
TIC ID 387690507: First sector 6
TIC ID 438490744: First sector 6
TIC ID 218795833: First sector 7
TIC ID 348538431: First sector 7
TIC ID 431999925: First sector 7
TIC ID 27649847: First sector 7
TIC ID 296739893: First sector 8
TIC ID 296780789: First sector 8
TIC ID 82362447: First sector 8
TIC ID 146463781: First sector 7
TIC ID 413248763: First sector 8
TIC ID 119081096: First sector 8
TIC ID 150428135: First sector 1
TIC ID 158588995: First sector 9
TIC ID 54962195: First sector 9
TIC ID 151825527: First sector 9
TIC ID 35009898: First sector 9
TIC ID 54962195: First sector 9
TIC ID 447061717: First sector 9
TIC ID 101955023: First sector 9
TIC ID 219195044: First sector 1
TIC ID 237920046: First sector 1
TIC ID 271971130: First sector 1
TIC ID 149788158: First sector 8
TIC ID 231728511: First sector 4
TIC ID 77156829: First sector 4
TIC ID 271596225: First sector 1
TIC ID 150428135: First sector 1
TIC ID 34068865: First sector 9
TIC ID 36724087: First sector 9
TIC ID 181804752: First sector 9
TIC ID 181804752: First sector 9
TIC ID 36724087: First sector 9
TIC ID 359271092: First sector 9
TIC ID 219195044: First sector 1
TIC ID 271596225: First sector 1
TIC ID 300710077: First sector 1
TIC ID 374829238: First sector 2
TIC ID 38460940: First sector 1
TIC ID 5868998: First sector 10
TIC ID 178709444: First sector 10
TIC ID 429358906: First sector 10
TIC ID 306996324: First sector 10
TIC ID 306996324: First sector 10
TIC ID 92226327: First sector 3
TIC ID 260708537: First sector 1
TIC ID 73649615: First sector 10
TIC ID 200322593: First sector 4
TIC ID 432008938: First sector 7
TIC ID 307210830: First sector 2
TIC ID 141608198: First sector 1
TIC ID 307210830: First sector 2
TIC ID 277634430: First sector 10
TIC ID 125405602: First sector 11
TIC ID 166184426: First sector 11
TIC ID 261257684: First sector 12
TIC ID 248250955: First sector 12
TIC ID 369327947: First sector 12
TIC ID 406941612: First sector 12
TIC ID 70797900: First sector 2
TIC ID 90504905: First sector 14
TIC ID 219698776: First sector 14
TIC ID 229781583: First sector 14
TIC ID 274762761: First sector 14
TIC ID 467179528: First sector 14
TIC ID 163539739: First sector 15
TIC ID 267561446: First sector 15
TIC ID 274662200: First sector 15
TIC ID 408203470: First sector 14
TIC ID 453260209: First sector 10
TIC ID 360156606: First sector 11
TIC ID 370133522: First sector 13
TIC ID 161032923: First sector 13
TIC ID 351601843: First sector 13
TIC ID 322270620: First sector 12
TIC ID 300710077: First sector 1
TIC ID 300710077: First sector 1
TIC ID 467179528: First sector 14
TIC ID 13684720: First sector 14
TIC ID 235683377: First sector 14
TIC ID 259168516: First sector 14
TIC ID 377293776: First sector 14
TIC ID 343628284: First sector 15
TIC ID 420112589: First sector 14
TIC ID 284441182: First sector 17
TIC ID 427654774: First sector 17
TIC ID 240968774: First sector 17
TIC ID 243185500: First sector 17
TIC ID 243185500: First sector 17
TIC ID 424747720: First sector 13
TIC ID 201186294: First sector 18
TIC ID 51024887: First sector 18
TIC ID 396562848: First sector 18
TIC ID 28900646: First sector 19
TIC ID 470381900: First sector 19
TIC ID 353475866: First sector 19
TIC ID 422756130: First sector 18
TIC ID 81212286: First sector 20
TIC ID 318022259: First sector 20
TIC ID 318022259: First sector 20
TIC ID 232635922: First sector 14
TIC ID 219860288: First sector 15
TIC ID 232650365: First sector 14
TIC ID 233602827: First sector 14
TIC ID 233602827: First sector 14
TIC ID 287139872: First sector 14
TIC ID 332477926: First sector 14
TIC ID 364074068: First sector 17
TIC ID 420112587: First sector 14
TIC ID 441739871: First sector 14
TIC ID 67646988: First sector 21
TIC ID 348755728: First sector 8
TIC ID 359357695: First sector 11
TIC ID 119584412: First sector 22
TIC ID 138762614: First sector 22
TIC ID 166648874: First sector 22
TIC ID 138819293: First sector 22
TIC ID 390651552: First sector 23
TIC ID 198385543: First sector 17
TIC ID 236387002: First sector 24
TIC ID 142748283: First sector 14
TIC ID 142748283: First sector 14
TIC ID 224298134: First sector 15
TIC ID 198485881: First sector 14
TIC ID 321669174: First sector 14
TIC ID 235678745: First sector 14
TIC ID 356016119: First sector 14
TIC ID 235678745: First sector 14
TIC ID 417931300: First sector 14
TIC ID 356871098: First sector 14
TIC ID 441738827: First sector 15
TIC ID 441738827: First sector 15
TIC ID 188589164: First sector 24
TIC ID 368287008: First sector 24
TIC ID 405763009: First sector 14
TIC ID 389900760: First sector 18
TIC ID 44313455: First sector 26
TIC ID 336128819: First sector 26
TIC ID 287139872: First sector 14
TIC ID 8348911: First sector 24
TIC ID 71347873: First sector 20
TIC ID 243313296: First sector 14
TIC ID 236934937: First sector 15
TIC ID 441798995: First sector 14
TIC ID 329148988: First sector 16
TIC ID 321688498: First sector 17
TIC ID 38680052: First sector 1
TIC ID 459837008: First sector 19
TIC ID 441798995: First sector 14
TIC ID 168751223: First sector 4
TIC ID 212957629: First sector 3
TIC ID 29959760: First sector 4
TIC ID 153078576: First sector 3
TIC ID 219175972: First sector 1
TIC ID 439867639: First sector 4
TIC ID 4294779: First sector 6
TIC ID 170789802: First sector 5
TIC ID 59128183: First sector 5
TIC ID 434260570: First sector 5
TIC ID 33091590: First sector 7
TIC ID 160328683: First sector 6
TIC ID 261135533: First sector 15
TIC ID 146776480: First sector 8
TIC ID 176772671: First sector 8
TIC ID 135036669: First sector 9
TIC ID 302527524: First sector 9
TIC ID 243641947: First sector 11
TIC ID 165827520: First sector 11
TIC ID 305478010: First sector 15
TIC ID 155867025: First sector 19
TIC ID 458419328: First sector 20
TIC ID 86263325: First sector 22
TIC ID 20182780: First sector 23
TIC ID 141616639: First sector 19
TIC ID 434105094: First sector 2
TIC ID 219175972: First sector 1
TIC ID 271596225: First sector 1
TIC ID 77156829: First sector 4
TIC ID 54962195: First sector 9
TIC ID 153065527: First sector 3
TIC ID 149788158: First sector 8
TIC ID 44898913: First sector 4
TIC ID 176797879: First sector 4
TIC ID 62301521: First sector 13
TIC ID 354944123: First sector 13
TIC ID 354944123: First sector 13
TIC ID 313889049: First sector 2
TIC ID 408416746: First sector 8
TIC ID 4070275: First sector 5
TIC ID 52307802: First sector 1
TIC ID 271169413: First sector 11
TIC ID 140687214: First sector 1
TIC ID 166184428: First sector 11
TIC ID 22233480: First sector 40
TIC ID 230129753: First sector 14
TIC ID 348054109: First sector 26
TIC ID 193336820: First sector 14
TIC ID 239332587: First sector 15
TIC ID 126606859: First sector 15
TIC ID 12938488: First sector 41
TIC ID 39926974: First sector 42
TIC ID 380887434: First sector 42
TIC ID 384888319: First sector 42
TIC ID 261257684: First sector 12
TIC ID 150428135: First sector 1
TIC ID 381897917: First sector 13
TIC ID 149126400: First sector 1
TIC ID 107018378: First sector 10
TIC ID 298428237: First sector 14
TIC ID 103605399: First sector 14
TIC ID 154940895: First sector 19
TIC ID 137683938: First sector 14
TIC ID 307809773: First sector 43
TIC ID 286201103: First sector 15
TIC ID 307809773: First sector 43
TIC ID 232650365: First sector 14
TIC ID 459837008: First sector 19
TIC ID 224298134: First sector 15
TIC ID 258796169: First sector 17
TIC ID 94727308: First sector 43
TIC ID 336961891: First sector 42
TIC ID 270355392: First sector 4
TIC ID 203214081: First sector 44
TIC ID 19028197: First sector 44
TIC ID 150096001: First sector 43
TIC ID 184892124: First sector 44
TIC ID 434226736: First sector 44
TIC ID 142938659: First sector 4
TIC ID 165202476: First sector 31
TIC ID 404506270: First sector 4
TIC ID 60074373: First sector 7
TIC ID 143032776: First sector 36
TIC ID 335590096: First sector 10
TIC ID 262499797: First sector 3
TIC ID 324609476: First sector 27
TIC ID 318180448: First sector 13
TIC ID 203289099: First sector 44
TIC ID 213111428: First sector 12
TIC ID 173103335: First sector 45
TIC ID 277833995: First sector 8
TIC ID 95337971: First sector 45
TIC ID 437054764: First sector 44
TIC ID 318022259: First sector 20
TIC ID 264301607: First sector 14
TIC ID 147892178: First sector 14
TIC ID 419411415: First sector 15
TIC ID 4619242: First sector 42
TIC ID 246965431: First sector 18
TIC ID 33397739: First sector 42
TIC ID 250111245: First sector 42
TIC ID 202468443: First sector 15
TIC ID 126982221: First sector 42
TIC ID 16005254: First sector 43
TIC ID 26054627: First sector 42
TIC ID 90767677: First sector 18
TIC ID 407591297: First sector 21
TIC ID 171646471: First sector 22
TIC ID 39143128: First sector 22
TIC ID 56798909: First sector 44
TIC ID 443582629: First sector 9
TIC ID 389040826: First sector 8
TIC ID 377097547: First sector 45
TIC ID 291109653: First sector 23
TIC ID 270355392: First sector 4
TIC ID 468983280: First sector 7
TIC ID 443616612: First sector 9
TIC ID 443616612: First sector 9
TIC ID 244170332: First sector 3
TIC ID 345450130: First sector 5
TIC ID 458686847: First sector 34
TIC ID 87405719: First sector 45
TIC ID 387974148: First sector 43
TIC ID 330637910: First sector 44
TIC ID 388804061: First sector 45
TIC ID 323687123: First sector 44
TIC ID 237108775: First sector 14
TIC ID 252481136: First sector 21
TIC ID 160162137: First sector 14
TIC ID 252928337: First sector 20
TIC ID 141202786: First sector 22
TIC ID 119585136: First sector 22
TIC ID 459762279: First sector 20
TIC ID 23863105: First sector 16
TIC ID 198162530: First sector 14
TIC ID 310380289: First sector 16
TIC ID 157769780: First sector 14
TIC ID 219875976: First sector 14
TIC ID 298074836: First sector 14
TIC ID 230055368: First sector 22
TIC ID 103865797: First sector 25
TIC ID 147923561: First sector 14
TIC ID 4918918: First sector 21
TIC ID 219041246: First sector 16
TIC ID 286813592: First sector 22
TIC ID 138820713: First sector 22
TIC ID 166648874: First sector 22
TIC ID 166648874: First sector 22
TIC ID 193634953: First sector 25
TIC ID 120045750: First sector 14
TIC ID 289666986: First sector 19
TIC ID 72889156: First sector 25
TIC ID 328081248: First sector 54
TIC ID 264468702: First sector 18
TIC ID 354727907: First sector 14
TIC ID 434116397: First sector 56
TIC ID 354173595: First sector 42
TIC ID 296898634: First sector 15
TIC ID 305506996: First sector 55
TIC ID 329709756: First sector 15
TIC ID 236785891: First sector 14
TIC ID 14956304: First sector 14
TIC ID 258037656: First sector 55
TIC ID 353146308: First sector 55
TIC ID 380517859: First sector 15
TIC ID 259233660: First sector 14
TIC ID 102734241: First sector 14
TIC ID 279922257: First sector 18
TIC ID 446157122: First sector 19
TIC ID 48353358: First sector 14
TIC ID 339591840: First sector 53
TIC ID 18318288: First sector 25
TIC ID 233602827: First sector 14
TIC ID 198162530: First sector 14
TIC ID 7439480: First sector 11
TIC ID 388076422: First sector 16
TIC ID 455947620: First sector 16
TIC ID 435878153: First sector 17
TIC ID 459837008: First sector 19
TIC ID 455947620: First sector 16
TIC ID 52005579: First sector 42
TIC ID 321669174: First sector 14
TIC ID 44295981: First sector 56
TIC ID 404456775: First sector 56
TIC ID 86005116: First sector 55
TIC ID 288144647: First sector 57
TIC ID 352147273: First sector 17
TIC ID 286763141: First sector 9
TIC ID 85281192: First sector 17
TIC ID 186715217: First sector 18
TIC ID 308120029: First sector 18
TIC ID 372207328: First sector 16
TIC ID 16550540: First sector 60
TIC ID 328513434: First sector 19
TIC ID 459982699: First sector 14
TIC ID 122798633: First sector 7
TIC ID 168936945: First sector 7
TIC ID 274002141: First sector 19
TIC ID 259502942: First sector 19
TIC ID 166145361: First sector 11
TIC ID 332657786: First sector 8
TIC ID 184801054: First sector 34
TIC ID 376800517: First sector 10
TIC ID 445522339: First sector 7
TIC ID 47143972: First sector 8
TIC ID 45881495: First sector 9
TIC ID 356921678: First sector 9
TIC ID 382187347: First sector 1
TIC ID 142277868: First sector 10
TIC ID 22560356: First sector 10
TIC ID 144077896: First sector 10
TIC ID 148691985: First sector 38
TIC ID 160442729: First sector 11
TIC ID 349503728: First sector 12
TIC ID 167573692: First sector 1
TIC ID 418343229: First sector 19
TIC ID 112115898: First sector 7
TIC ID 261264800: First sector 1
TIC ID 34986694: First sector 9
TIC ID 269849065: First sector 1
TIC ID 443823169: First sector 7
TIC ID 303364023: First sector 9
TIC ID 299798795: First sector 1
TIC ID 32090583: First sector 1
TIC ID 262470965: First sector 67
TIC ID 349891396: First sector 13
TIC ID 383313006: First sector 13
TIC ID 291013124: First sector 27
TIC ID 261679541: First sector 1
TIC ID 344552721: First sector 13
TIC ID 230982415: First sector 2
TIC ID 201254754: First sector 1
TIC ID 281596890: First sector 2
TIC ID 28872266: First sector 42
TIC ID 83181153: First sector 43
TIC ID 63100069: First sector 71
TIC ID 67512645: First sector 22
TIC ID 421006834: First sector 7
TIC ID 337217173: First sector 4
TIC ID 468983280: First sector 7
TIC ID 57147191: First sector 44
TIC ID 11894726: First sector 22
TIC ID 219707850: First sector 14
TIC ID 446166017: First sector 22
TIC ID 22740615: First sector 22
TIC ID 364571121: First sector 15
TIC ID 376354189: First sector 18
TIC ID 272829240: First sector 17
TIC ID 459323923: First sector 25
TIC ID 288421619: First sector 82
TIC ID 341005781: First sector 15
TIC ID 277853911: First sector 15
TIC ID 268727719: First sector 17
TIC ID 77490011: First sector 18
TIC ID 258776466: First sector 14
TIC ID 198358065: First sector 14
TIC ID 18885659: First sector 80
TIC ID 160075684: First sector 14
TIC ID 282113152: First sector 55
TIC ID 161687285: First sector 15
TIC ID 219089784: First sector 15
TIC ID 275717567: First sector 15
TIC ID 83299322: First sector 14
TIC ID 161687211: First sector 15
TIC ID 73729607: First sector 58
TIC ID 154480367: First sector 16
TIC ID 374177909: First sector 16
TIC ID 374173310: First sector 16
TIC ID 73692250: First sector 18
TIC ID 233747840: First sector 14
TIC ID 251090642: First sector 21
TIC ID 192833836: First sector 5
TIC ID 76835246: First sector 92
TIC ID 111778581: First sector 2

AttributeError: 'list' object has no attribute 'head'

In [24]:
print(results)

[      tic_id                              sectors  n_sectors pipelines  \
0  410153553  1,27,28,67,68,94,95,101,102,103,104         11    [SPOC]

     P_days           T0  depth_frac  duration_hr
0  0.462931  1325.724661    0.004678     0.631015  ,       tic_id                 sectors  n_sectors   pipelines    P_days  \
0  234994474  1,28,68,95,102,104,105          7  [SPOC/QLP]  1.401518

            T0  depth_frac  duration_hr
0  1326.034032    0.000594     1.158306  ,       tic_id                    sectors  n_sectors pipelines    P_days  \
0  206609630  1,2,28,29,68,69,95,96,104          9    [SPOC]  0.335272

            T0  depth_frac  duration_hr
0  1325.490344    0.019688     0.718986  ,       tic_id                           sectors  n_sectors pipelines    P_days  \
0  231702397  1,27,28,67,68,95,102,103,104,105         10    [SPOC]  5.078033

            T0  depth_frac  duration_hr
0  1329.118988    0.005923     1.210035  ,       tic_id                        sectors  n_sectors pipelines    P_days  \
0  234523599  1,2,28,29,68,69,95,96,103,104         10    [SPOC]  3.795518

            T0  depth_frac  duration_hr
0  1325.650603    0.052279     2.019813  ,       tic_id                       sectors  n_sectors pipelines     P_days  \
0  299798795  1,13,27,28,39,66,67,68,93,95         10    [SPOC]   4.178266
1  299798795  1,13,27,28,39,66,67,68,93,95         10    [SPOC]  17.945364

            T0  depth_frac  duration_hr
0  1327.705053    0.002538     1.675904
1  1329.862603    0.005481     3.074007  ,       tic_id                       sectors  n_sectors pipelines    P_days  \
0  394357918  1,13,28,39,66,68,89,93,94,95         10    [SPOC]  4.901994

            T0  depth_frac  duration_hr
0  1326.789691    0.010775      1.32438  ,      tic_id         sectors  n_sectors pipelines     P_days         T0  \
0  12421862  2,29,69,96,107          5     [QLP]  10.215017  1356.3672

   depth_frac  duration_hr
0    0.000994     1.968307  ,       tic_id                       sectors  n_sectors   pipelines    P_days  \
0  262530407  2,3,29,69,96,103,104,105,106          9  [SPOC/QLP]  2.853102

            T0  depth_frac  duration_hr
0  3204.963281    0.001395        1.142  ,       tic_id                                            sectors  n_sectors  \
0  307210830  2,5,8,9,10,11,12,28,29,32,35,36,37,38,39,61,62...         27
1  307210830  2,5,8,9,10,11,12,28,29,32,35,36,37,38,39,61,62...         27
2  307210830  2,5,8,9,10,11,12,28,29,32,35,36,37,38,39,61,62...         27

    pipelines    P_days           T0  depth_frac  duration_hr
0       [QLP]  3.690676  3688.708370    0.001657     1.107000
1  [SPOC/QLP]  2.253106  1354.907237    0.000682     0.993984
2  [SPOC/QLP]  7.450730  3039.154503    0.001542     0.475000  ,       tic_id                                            sectors  n_sectors  \
0  141527579  1,2,3,4,5,7,8,9,10,11,12,13,27,28,29,30,31,32,...         44

  pipelines     P_days           T0  depth_frac  duration_hr
0    [SPOC]  15.086774  1328.941861    0.001912     2.125029  ,      tic_id                                            sectors  n_sectors  \
0  32090583  1,2,2,3,4,6,7,8,9,10,11,12,13,27,28,29,30,31,3...         43
1  32090583  1,2,2,3,4,6,7,8,9,10,11,12,13,27,28,29,30,31,3...         43

  pipelines    P_days           T0  depth_frac  duration_hr
0    [SPOC]  0.438481  1325.547997    0.000486     0.519294
1    [SPOC]  8.352214  1328.408317    0.003925     1.663712  ,      tic_id                                            sectors  n_sectors  \
0  55650590  1,2,3,4,5,6,7,8,9,10,11,12,13,27,28,29,30,31,3...         44

  pipelines    P_days           T0  depth_frac  duration_hr
0    [SPOC]  0.736313  1325.542536    0.001323     0.673685  ,       tic_id                                            sectors  n_sectors  \
0  237914496  1,2,3,4,7,11,27,28,29,30,31,34,37,61,62,63,64,...         28

  pipelines    P_days          T0  depth_frac  duration_hr
0    [SPOC]  3.568141  1326.81595    0.000907     1.455634  ,       tic_id             sectors  n_sectors pipelines    P_days           T0  \
0  305048087  2,29,69,96,106,107          6    [SPOC]  5.436167  1355.241753

   depth_frac  duration_hr
0    0.004797     1.541967  ,       tic_id                                            sectors  n_sectors  \
0  260004324  1,2,3,4,5,7,8,9,10,11,12,13,27,28,29,30,31,32,...         42

    pipelines    P_days           T0  depth_frac  duration_hr
0  [SPOC/QLP]  3.814301  1327.416979    0.000458     1.379395  ,       tic_id                     sectors  n_sectors pipelines    P_days  \
0  118327550  2,29,69,96,104,105,106,107          8    [SPOC]  7.397216

            T0  depth_frac  duration_hr
0  1357.364688    0.000954     1.316496  ,      tic_id         sectors  n_sectors pipelines    P_days           T0  \
0  12423815  2,29,69,96,107          5    [SPOC]  2.839279  1356.087715

   depth_frac  duration_hr
0     0.03523     1.401179  ,       tic_id              sectors  n_sectors pipelines     P_days  \
0  415969908  2,29,42,69,70,92,96          7    [SPOC]  11.670029
1  415969908  2,29,42,69,70,92,96          7    [SPOC]   7.201138

            T0  depth_frac  duration_hr
0  1365.261451    0.002784     2.053414
1  1359.471437    0.001663     2.144468  ,       tic_id            sectors  n_sectors pipelines   P_days           T0  \
0  120916706  3,4,30,97,105,107          6    [SPOC]  0.55681  2116.147851

   depth_frac  duration_hr
0    0.045141     0.971207  ,       tic_id                                            sectors  n_sectors  \
0  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37
1  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37
2  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37
3  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37

  pipelines     P_days           T0  depth_frac  duration_hr
0    [SPOC]  16.051106  2303.157062    0.002769     1.396823
1    [SPOC]  37.423684  1330.486155    0.000738     3.365010
2    [SPOC]   9.977273  1331.349645    0.000460     2.258363
3    [SPOC]  27.809690  1352.999520    0.000407     2.955882  ,       tic_id              sectors  n_sectors pipelines     P_days  \
0  415969908  2,29,42,69,70,92,96          7    [SPOC]  11.670029
1  415969908  2,29,42,69,70,92,96          7    [SPOC]   7.201138

            T0  depth_frac  duration_hr
0  1365.261451    0.002784     2.053414
1  1359.471437    0.001663     2.144468  ,       tic_id                   sectors  n_sectors pipelines     P_days  \
0  153065527  3,4,30,31,97,105,106,107          8    [SPOC]  13.175729
1  153065527  3,4,30,31,97,105,106,107          8    [SPOC]   6.614911

           T0  depth_frac  duration_hr
0  1388.56746    0.002479     2.157027
1  1385.38837    0.001061     0.965460  ,       tic_id                                            sectors  n_sectors  \
0  220479565  3,4,5,6,10,13,30,31,32,33,36,63,64,66,67,87,90...         21

  pipelines    P_days           T0  depth_frac  duration_hr
0    [SPOC]  3.697717  1381.845549    0.004756     0.930826  ,       tic_id            sectors  n_sectors pipelines     P_days           T0  \
0  259377017  3,4,5,30,32,97,98          7    [SPOC]   5.660569  2198.961454
1  259377017  3,4,5,30,32,97,98          7    [SPOC]  11.379565  1389.679336
2  259377017  3,4,5,30,32,97,98          7    [SPOC]   3.360138  1383.733214

   depth_frac  duration_hr
0    0.003856     1.663170
1    0.003147     2.235031
2    0.000973     1.413245  ,       tic_id            sectors  n_sectors pipelines     P_days           T0  \
0  259377017  3,4,5,30,32,97,98          7    [SPOC]   5.660569  2198.961454
1  259377017  3,4,5,30,32,97,98          7    [SPOC]  11.379565  1389.679336
2  259377017  3,4,5,30,32,97,98          7    [SPOC]   3.360138  1383.733214

   depth_frac  duration_hr
0    0.003856     1.663170
1    0.003147     2.235031
2    0.000973     1.413245  ,       tic_id            sectors  n_sectors pipelines     P_days           T0  \
0  259377017  3,4,5,30,32,97,98          7    [SPOC]   5.660569  2198.961454
1  259377017  3,4,5,30,32,97,98          7    [SPOC]  11.379565  1389.679336
2  259377017  3,4,5,30,32,97,98          7    [SPOC]   3.360138  1383.733214

   depth_frac  duration_hr
0    0.003856     1.663170
1    0.003147     2.235031
2    0.000973     1.413245  ,      tic_id   sectors  n_sectors pipelines     P_days           T0  \
0  92226327  3,30,107          3    [SPOC]   3.777942  2141.100488
1  92226327  3,30,107          3    [SPOC]  24.737341  1399.928643

   depth_frac  duration_hr
0    0.003469     1.475933
1    0.006560     2.069051  ,       tic_id      sectors  n_sectors pipelines    P_days           T0  \
0  439456714  3,30,97,107          4    [SPOC]  3.993442  1385.036312

   depth_frac  duration_hr
0    0.005802     1.969306  ,       tic_id  sectors  n_sectors pipelines    P_days           T0  depth_frac  \
0  244161191  3,30,70          3    [SPOC]  0.299039  1381.910527    0.005781

   duration_hr
0      0.72181  ,      tic_id sectors  n_sectors   pipelines    P_days           T0  depth_frac  \
0  98796344    4,31          2  [SPOC/QLP]  5.358776  2168.295274    0.002708

   duration_hr
0     1.369776  ,       tic_id                   sectors  n_sectors   pipelines     P_days  \
0  153077621  3,4,30,31,97,105,106,107          8  [SPOC/QLP]  18.082608

           T0  depth_frac  duration_hr
0  1396.13818    0.008003     2.386799  ,      tic_id sectors  n_sectors   pipelines    P_days           T0  depth_frac  \
0  29960110    4,31          2  [SPOC/QLP]  2.491977  1411.670877    0.002094

   duration_hr
0     1.433814  ,      tic_id         sectors  n_sectors pipelines    P_days           T0  \
0  44737596  4,5,31,106,107          5    [SPOC]  2.788654  1413.060435

   depth_frac  duration_hr
0     0.02634     1.890019  ,      tic_id           sectors  n_sectors pipelines    P_days           T0  \
0  77156829  4,5,31,32,98,107          6    [SPOC]  0.860241  1411.473627
1  77156829  4,5,31,32,98,107          6    [SPOC]  3.694260  1411.067517
2  77156829  4,5,31,32,98,107          6    [SPOC]  4.965207  1414.562933

   depth_frac  duration_hr
0    0.000720     0.512434
1    0.000833     1.127852
2    0.000633     0.936152  ,      tic_id       sectors  n_sectors pipelines    P_days           T0  \
0  89256802  4,31,106,107          4    [SPOC]  1.175983  1411.560535

   depth_frac  duration_hr
0    0.014881     0.992834  ,      tic_id            sectors  n_sectors   pipelines     P_days           T0  \
0  77951245  5,6,32,98,106,107          6  [SPOC/QLP]  10.714866  2182.487384

   depth_frac  duration_hr
0    0.056326     2.112158  ,      tic_id    sectors  n_sectors   pipelines   P_days           T0  \
0  52280468  6,7,33,87          4  [SPOC/QLP]  0.56826  2226.783631

   depth_frac  duration_hr
0     0.04254        0.755  ,      tic_id            sectors  n_sectors pipelines   P_days           T0  \
0  33521996  6,32,33,87,98,107          6    [SPOC]  3.32527  2220.820401

   depth_frac  duration_hr
0    0.034742     2.053814  ,      tic_id sectors  n_sectors pipelines    P_days           T0  depth_frac  \
0  55488511    5,31          2    [SPOC]  3.344904  1439.549649    0.001399

   duration_hr
0     1.340835  ,      tic_id  sectors  n_sectors pipelines    P_days           T0  depth_frac  \
0  53593457  6,33,87          3    [SPOC]  0.530893  1468.332102    0.033454

   duration_hr
0     1.910177  ,       tic_id     sectors  n_sectors pipelines    P_days           T0  \
0  200593988  6,71,72,98          4    [SPOC]  7.699087  1470.849292

   depth_frac  duration_hr
0    0.008072     4.380607  ,       tic_id  sectors  n_sectors pipelines    P_days           T0  depth_frac  \
0  202185707  6,33,87          3    [SPOC]  1.650067  1469.368876     0.00271

   duration_hr
0     0.919868  ,      tic_id            sectors  n_sectors pipelines    P_days           T0  \
0  32830028  6,32,33,87,98,107          6    [SPOC]  0.516278  1468.344415

   depth_frac  duration_hr
0    0.020289     0.565611  ,       tic_id  sectors  n_sectors pipelines    P_days           T0  depth_frac  \
0  237751146  6,33,87          3    [SPOC]  1.669769  2203.397714    0.010666

   duration_hr
0     2.010535  ,       tic_id              sectors  n_sectors pipelines    P_days           T0  \
0  192826603  5,6,32,33,87,98,107          7    [SPOC]  2.647305  2203.149174

   depth_frac  duration_hr
0    0.021368     1.211281  ,       tic_id           sectors  n_sectors pipelines    P_days           T0  \
0  302895996  6,43,44,45,71,98          6    [SPOC]  0.567995  1468.847149

   depth_frac  duration_hr
0    0.005209     1.408867  ,       tic_id     sectors  n_sectors pipelines  P_days           T0  \
0  452866790  7,34,61,88          4    [SPOC]   1.198  1492.205829

   depth_frac  duration_hr
0     0.00115       0.9682  ,       tic_id              sectors  n_sectors pipelines    P_days           T0  \
0  387690507  6,33,44,45,71,72,87          7    [SPOC]  6.387574  1470.202595

   depth_frac  duration_hr
0    0.023994     2.566058  ,       tic_id           sectors  n_sectors pipelines    P_days         T0  \
0  438490744  6,43,44,45,71,72          6    [SPOC]  1.665878  1468.4958

   depth_frac  duration_hr
0    0.085644     4.956738  ,       tic_id       sectors  n_sectors pipelines    P_days           T0  \
0  218795833  7,8,34,61,88          5    [SPOC]  1.265234  1491.877056

   depth_frac  duration_hr
0    0.110216       1.2121  ,       tic_id     sectors  n_sectors pipelines    P_days           T0  \
0  348538431  7,34,61,88          4    [SPOC]  0.899468  2963.623366

   depth_frac  duration_hr
0    0.058768     1.206667  ,       tic_id     sectors  n_sectors pipelines    P_days          T0  \
0  431999925  7,34,61,88          4    [SPOC]  1.445433  1492.93007

   depth_frac  duration_hr
0    0.016635     3.684343  ,      tic_id              sectors  n_sectors pipelines    P_days           T0  \
0  27649847  7,34,44,45,46,71,72          7    [SPOC]  1.542849  1492.716411

   depth_frac  duration_hr
0    0.002154      1.19589  ,       tic_id        sectors  n_sectors   pipelines    P_days           T0  \
0  296739893  8,35,62,89,99          5  [SPOC/QLP]  5.098804  1518.004514

   depth_frac  duration_hr
0    0.002926     1.025282  ,       tic_id        sectors  n_sectors pipelines     P_days           T0  \
0  296780789  8,35,62,89,99          5    [SPOC]  13.577343  1524.632416

   depth_frac  duration_hr
0    0.156035     1.724522  ,      tic_id           sectors  n_sectors pipelines    P_days           T0  \
0  82362447  8,35,61,62,88,89          6    [SPOC]  2.819817  1517.560677

   depth_frac  duration_hr
0    0.183631     6.611278  ,       tic_id          sectors  n_sectors pipelines    P_days           T0  \
0  146463781  7,8,34,35,61,88          6    [SPOC]  0.417921  1517.476816

   depth_frac  duration_hr
0    0.041645     1.843947  ,       tic_id        sectors  n_sectors pipelines    P_days           T0  \
0  413248763  8,35,62,89,99          5    [SPOC]  3.930603  3011.629018

   depth_frac  duration_hr
0    0.001048        1.196  ,       tic_id           sectors  n_sectors pipelines   P_days          T0  \
0  119081096  8,35,61,62,89,99          6     [QLP]  0.83707  1518.10991

   depth_frac  duration_hr
0    0.002746        2.497  ,       tic_id                                            sectors  n_sectors  \
0  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37
1  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37
2  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37
3  150428135  1,3,4,5,6,7,8,9,10,11,13,27,28,30,31,33,34,35,...         37

  pipelines     P_days           T0  depth_frac  duration_hr
0    [SPOC]  16.051106  2303.157062    0.002769     1.396823
1    [SPOC]  37.423684  1330.486155    0.000738     3.365010
2    [SPOC]   9.977273  1331.349645    0.000460     2.258363
3    [SPOC]  27.809690  1352.999520    0.000407     2.955882  ,       tic_id               sectors  n_sectors   pipelines    P_days  \
0  158588995  9,10,36,63,90,99,100          7  [SPOC/QLP]  1.977166

            T0  depth_frac  duration_hr
0  2301.778142    0.013877     1.110415  ,      tic_id         sectors  n_sectors   pipelines    P_days           T0  \
0  54962195  9,35,62,89,100          5  [SPOC/QLP]  2.598903  1544.387711
1  54962195  9,35,62,89,100          5  [SPOC/QLP]  4.695599  1543.405068
2  54962195  9,35,62,89,100          5      [SPOC]  7.102475  1547.138797

   depth_frac  duration_hr
0    0.001953     1.663571
1    0.001969     2.163872
2    0.001318     2.754265  ,       tic_id               sectors  n_sectors   pipelines    P_days  \
0  151825527  9,10,36,63,90,99,100          7  [SPOC/QLP]  3.633583

            T0  depth_frac  duration_hr
0  1546.478904    0.008668     1.806969  ,      tic_id                  sectors  n_sectors   pipelines    P_days  \
0  35009898  9,36,45,46,62,72,89,100          8  [SPOC/QLP]  1.527564

            T0  depth_frac  duration_hr
0  1543.433731    0.002892     1.372705  ,      tic_id         sectors  n_sectors   pipelines    P_days           T0  \
0  54962195  9,35,62,89,100          5  [SPOC/QLP]  2.598903  1544.387711
1  54962195  9,35,62,89,100          5  [SPOC/QLP]  4.695599  1543.405068
2  54962195  9,35,62,89,100          5      [SPOC]  7.102475  1547.138797

   depth_frac  duration_hr
0    0.001953     1.663571
1    0.001969     2.163872
2    0.001318     2.754265  ,       tic_id              sectors  n_sectors pipelines     P_days  \
0  447061717  9,10,36,37,63,90,99          7     [QLP]  24.245497

            T0  depth_frac  duration_hr
0  1563.890468    0.006261     3.372558  ,       tic_id           sectors  n_sectors   pipelines    P_days           T0  \
0  101955023  9,10,36,63,90,99          6  [SPOC/QLP]  1.628932  2280.989404

   depth_frac  duration_hr
0    0.002512     0.809276  ,       tic_id                                            sectors  n_sectors  \
0  219195044  1,2,4,5,6,7,8,11,12,28,29,31,32,33,34,35,38,61...         30
1  219195044  1,2,4,5,6,7,8,11,12,28,29,31,32,33,34,35,38,61...         30

    pipelines     P_days           T0  depth_frac  duration_hr
0  [SPOC/QLP]   4.323933  1412.826255    0.000977     1.578313
1      [SPOC]  10.177547  1419.106130    0.000943     2.040166  ,       tic_id                                            sectors  n_sectors  \
0  237920046  1,2,3,4,11,28,29,30,31,34,38,61,62,64,65,68,69...         22

  pipelines  P_days           T0  depth_frac  duration_hr
0    [SPOC]  5.9312  1326.224903    0.001022     2.031449  ,       tic_id                                            sectors  n_sectors  \
0  271971130  1,2,3,4,5,6,7,8,9,10,11,12,13,27,29,30,31,32,3...         43

  pipelines     P_days           T0  depth_frac  duration_hr
0    [SPOC]  19.287958  1327.552087    0.004774     2.184164  ,       tic_id        sectors  n_sectors pipelines    P_days           T0  \
0  149788158  8,34,61,88,99          5     [QLP]  4.724444  2245.518460
1  149788158  8,34,61,88,99          5    [SPOC]  0.749971  1518.087839

   depth_frac  duration_hr
0    0.001480     0.999000
1    0.000442     1.057606  ,       tic_id                              sectors  n_sectors pipelines  \
0  231728511  4,5,6,27,31,32,33,37,64,67,87,94,98         13    [SPOC]

     P_days          T0  depth_frac  duration_hr
0  0.520671  1411.15307    0.000627     0.570816  ,      tic_id           sectors  n_sectors pipelines    P_days           T0  \
0  77156829  4,5,31,32,98,107          6    [SPOC]  0.860241  1411.473627
1  77156829  4,5,31,32,98,107          6    [SPOC]  3.694260  1411.067517
2  77156829  4,5,31,32,98,107          6    [SPOC]  4.965207  1414.562933

   depth_frac  duration_hr
0    0.000720     0.512434
1    0.000833     1.127852

note: there might be duplicate rows

In [22]:
combined = pd.concat(results, ignore_index=True)
combined.head()
len(combined)

601

In [9]:
tic_id = 206609630
row = df[df["TIC ID"] == tic_id]
row.head()

,Parameter Source Pipeline,Detection Pipeline(s),TIC ID,Full TOI ID,TOI Disposition,TIC Right Ascension,TIC Declination,TIC Right Ascension 2015.5,TIC Declination 2015.5,TMag Value,...,M_planet [ME],K_RV [m/s],TSM,ESM,Stellar Insolation [ergs/cm^2/s],Stellar Insolation [Earth Units],Sectors_Observed,Cameras,CCDs,EdgeWarn
2,spoc-s01-s69-b0A-APC,SPOC,206609630,212.01,PC,22.551,-59.5832,22.550065,-59.583245,12.186,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,"3,3,3,3,3,3,3,3,3","1,2,1,2,1,2,1,2,3","0,0,0,0,0,0,0,0,0"

In [19]:
row.columns.tolist()

['Parameter Source Pipeline',
 'Detection Pipeline(s)',
 'TIC ID',
 'Full TOI ID',
 'TOI Disposition',
 'TIC Right Ascension',
 'TIC Declination',
 'TIC Right Ascension 2015.5',
 'TIC Declination 2015.5',
 'TMag Value',
 'TMag Uncertainty',
 'Orbital Epoch Value',
 'Epoch Uncertainty',
 'Orbital Period (days) Value',
 'Orbital Period Uncertainty',
 'Transit Duration (hours) Value',
 'Transit Duration (hours) Uncertainty',
 'Transit Depth Value',
 'Transit Depth Uncertainty',
 'Sectors',
 'Public Comment',
 'Surface Gravity Value',
 'Surface Gravity Uncertainty',
 'Planet Number',
 'Star Radius Value',
 'Star Radius Uncertainty',
 'Planet Radius Value',
 'Planet Radius Uncertainty',
 'Planet Equilibrium Temperature (K) Value',
 'Effective Temperature Value',
 'Effective Temperature Uncertainty',
 'Effective Stellar Flux Value',
 'Signal-to-noise',
 'Centroid Offset',
 'Master',
 'SG1a',
 'SG1b',
 'SG2',
 'SG3',
 'SG4',
 'SG5',
 'Alerted',
 'Updated',
 'ID',
 'ra',
 'dec',
 'pmRA',
 'pmDEC',
 'Tmag',
 'objType',
 'typeSrc',
 'version',
 'HIP',
 'TYC',
 'UCAC',
 'TWOMASS',
 'SDSS',
 'ALLWISE',
 'GAIA',
 'APASS',
 'KIC',
 'POSflag',
 'e_pmRA',
 'e_pmDEC',
 'PMflag',
 'plx',
 'e_plx',
 'PARflag',
 'gallong',
 'gallat',
 'eclong',
 'eclat',
 'Bmag',
 'e_Bmag',
 'Vmag',
 'e_Vmag',
 'umag',
 'e_umag',
 'gmag',
 'e_gmag',
 'rmag',
 'e_rmag',
 'imag',
 'e_imag',
 'zmag',
 'e_zmag',
 'Jmag',
 'e_Jmag',
 'Hmag',
 'e_Hmag',
 'Kmag',
 'e_Kmag',
 'TWOMflag',
 'prox',
 'w1mag',
 'e_w1mag',
 'w2mag',
 'e_w2mag',
 'w3mag',
 'e_w3mag',
 'w4mag',
 'e_w4mag',
 'GAIAmag',
 'e_GAIAmag',
 'e_Tmag',
 'TESSflag',
 'SPFlag',
 'Teff',
 'e_Teff',
 'logg',
 'e_logg',
 'MH',
 'e_MH',
 'rad',
 'e_rad',
 'mass',
 'e_mass',
 'rho',
 'e_rho',
 'lumclass',
 'lum',
 'e_lum',
 'd',
 'e_d',
 'ebv',
 'e_ebv',
 'numcont',
 'contratio',
 'disposition',
 'duplicate_id',
 'priority',
 'eneg_EBV',
 'epos_EBV',
 'EBVflag',
 'eneg_Mass',
 'epos_Mass',
 'eneg_Rad',
 'epos_Rad',
 'eneg_rho',
 'epos_rho',
 'eneg_logg',
 'epos_logg',
 'eneg_lum',
 'epos_lum',
 'eneg_dist',
 'epos_dist',
 'distflag',
 'eneg_Teff',
 'epos_Teff',
 'TeffFlag',
 'gaiabp',
 'e_gaiabp',
 'gaiarp',
 'e_gaiarp',
 'gaiaqflag',
 'starchareFlag',
 'VmagFlag',
 'BmagFlag',
 'splists',
 'e_RA',
 'e_Dec',
 'RA_orig',
 'Dec_orig',
 'e_RA_orig',
 'e_Dec_orig',
 'raddflag',
 'wdflag',
 'dstArcSec',
 'qld_a',
 'qld_b',
 'i',
 'M_planet [ME]',
 'K_RV [m/s]',
 'TSM',
 'ESM',
 'Stellar Insolation [ergs/cm^2/s]',
 'Stellar Insolation [Earth Units]',
 'Sectors_Observed',
 'Cameras',
 'CCDs',
 'EdgeWarn']