TESS Sectors Numbers for ```nearby_TOI_MDs.csv```

In [3]:
from toi_catalog import load_catalog, get_target_by_tic, style_target_df
import pandas as pd

manually selecting ```tic_id``` for this example

In [4]:
code_path = "/Users/madelinejmg/Desktop/PHYS39002/research2026/Catalog/nearby_TOI_MDs.csv"
df = load_catalog(code_path)

In [34]:
tic_id = 410153553
# checking how many sectors per target
params = get_target_by_tic(df, tic_id=tic_id, sector = None)
params

,tic_id,sectors,n_sectors,pipelines,P_days,T0,depth_frac,duration_hr
0,410153553,"1,27,28,67,68,94,95,101,102,103,104",11,[SPOC],0.462931,1325.724661,0.004678,0.631015

Grab the first number (the first LC per target star) for now

In [35]:
# grab the sectors string from the first matching row
sectors_str = df.loc[df["TIC ID"] == tic_id, "Sectors"].iloc[0]

# parse it into ints
sectors = [int(float(s.strip())) for s in str(sectors_str).split(",") if s.strip()]
print(f'TIC ID {tic_id}: Sector(s) {sectors}')

TIC ID 410153553: Sector(s) [1, 27, 28, 67, 68, 94, 95, 101, 102, 103, 104]

In [29]:
print(f'First number of TIC ID {tic_id}: Sector {sectors[0]}')

First number of TIC ID 410153553: Sector 1

----

In [36]:
for _, row in df.iterrows():
    
    tic_id = int(row["TIC ID"])
    
    sectors_str = row["Sectors"]
    
    if pd.isna(sectors_str):
        continue
    
    sectors = [int(float(s.strip())) 
               for s in str(sectors_str).split(",") 
               if s.strip()]
    
    if not sectors:
        continue
    
    first_sector = sectors[0]
    
    print(f"TIC {tic_id} -> First sector {first_sector}")

    params = get_target_by_tic(df, tic_id=tic_id, sector=first_sector)

TIC 410153553 -> First sector 1
TIC 234994474 -> First sector 1
TIC 206609630 -> First sector 1
TIC 231702397 -> First sector 1
TIC 234523599 -> First sector 1
TIC 299798795 -> First sector 1
TIC 394357918 -> First sector 1
TIC 12421862 -> First sector 2
TIC 262530407 -> First sector 2
TIC 307210830 -> First sector 2
TIC 141527579 -> First sector 1
TIC 32090583 -> First sector 1
TIC 55650590 -> First sector 1
TIC 237914496 -> First sector 1
TIC 305048087 -> First sector 2
TIC 260004324 -> First sector 1
TIC 118327550 -> First sector 2
TIC 12423815 -> First sector 2
TIC 415969908 -> First sector 2
TIC 120916706 -> First sector 3
TIC 150428135 -> First sector 1
TIC 415969908 -> First sector 2
TIC 153065527 -> First sector 3
TIC 220479565 -> First sector 3
TIC 259377017 -> First sector 3
TIC 259377017 -> First sector 3
TIC 259377017 -> First sector 3
TIC 92226327 -> First sector 3
TIC 439456714 -> First sector 3
TIC 244161191 -> First sector 3
TIC 98796344 -> First sector 4
TIC 153077621 -> First sector 3
TIC 29960110 -> First sector 4
TIC 44737596 -> First sector 4
TIC 77156829 -> First sector 4
TIC 89256802 -> First sector 4
TIC 77951245 -> First sector 5
TIC 52280468 -> First sector 6
TIC 33521996 -> First sector 6
TIC 55488511 -> First sector 5
TIC 53593457 -> First sector 6
TIC 200593988 -> First sector 6
TIC 202185707 -> First sector 6
TIC 32830028 -> First sector 6
TIC 237751146 -> First sector 6
TIC 192826603 -> First sector 5
TIC 302895996 -> First sector 6
TIC 452866790 -> First sector 7
TIC 387690507 -> First sector 6
TIC 438490744 -> First sector 6
TIC 218795833 -> First sector 7
TIC 348538431 -> First sector 7
TIC 431999925 -> First sector 7
TIC 27649847 -> First sector 7
TIC 296739893 -> First sector 8
TIC 296780789 -> First sector 8
TIC 82362447 -> First sector 8
TIC 146463781 -> First sector 7
TIC 413248763 -> First sector 8
TIC 119081096 -> First sector 8
TIC 150428135 -> First sector 1
TIC 158588995 -> First sector 9
TIC 54962195 -> First sector 9
TIC 151825527 -> First sector 9
TIC 35009898 -> First sector 9
TIC 54962195 -> First sector 9
TIC 447061717 -> First sector 9
TIC 101955023 -> First sector 9
TIC 219195044 -> First sector 1
TIC 237920046 -> First sector 1
TIC 271971130 -> First sector 1
TIC 149788158 -> First sector 8
TIC 231728511 -> First sector 4
TIC 77156829 -> First sector 4
TIC 271596225 -> First sector 1
TIC 150428135 -> First sector 1
TIC 34068865 -> First sector 9
TIC 36724087 -> First sector 9
TIC 181804752 -> First sector 9
TIC 181804752 -> First sector 9
TIC 36724087 -> First sector 9
TIC 359271092 -> First sector 9
TIC 219195044 -> First sector 1
TIC 271596225 -> First sector 1
TIC 300710077 -> First sector 1
TIC 374829238 -> First sector 2
TIC 38460940 -> First sector 1
TIC 5868998 -> First sector 10
TIC 178709444 -> First sector 10
TIC 429358906 -> First sector 10
TIC 306996324 -> First sector 10
TIC 306996324 -> First sector 10
TIC 92226327 -> First sector 3
TIC 260708537 -> First sector 1
TIC 73649615 -> First sector 10
TIC 200322593 -> First sector 4
TIC 432008938 -> First sector 7
TIC 307210830 -> First sector 2
TIC 141608198 -> First sector 1
TIC 307210830 -> First sector 2
TIC 277634430 -> First sector 10
TIC 125405602 -> First sector 11
TIC 166184426 -> First sector 11
TIC 261257684 -> First sector 12
TIC 248250955 -> First sector 12
TIC 369327947 -> First sector 12
TIC 406941612 -> First sector 12
TIC 70797900 -> First sector 2
TIC 90504905 -> First sector 14
TIC 219698776 -> First sector 14
TIC 229781583 -> First sector 14
TIC 274762761 -> First sector 14
TIC 467179528 -> First sector 14
TIC 163539739 -> First sector 15
TIC 267561446 -> First sector 15
TIC 274662200 -> First sector 15
TIC 408203470 -> First sector 14
TIC 453260209 -> First sector 10
TIC 360156606 -> First sector 11
TIC 370133522 -> First sector 13
TIC 161032923 -> First sector 13
TIC 351601843 -> First sector 13
TIC 322270620 -> First sector 12
TIC 300710077 -> First sector 1
TIC 300710077 -> First sector 1
TIC 467179528 -> First sector 14
TIC 13684720 -> First sector 14
TIC 235683377 -> First sector 14
TIC 259168516 -> First sector 14
TIC 377293776 -> First sector 14
TIC 343628284 -> First sector 15
TIC 420112589 -> First sector 14
TIC 284441182 -> First sector 17
TIC 427654774 -> First sector 17
TIC 240968774 -> First sector 17
TIC 243185500 -> First sector 17
TIC 243185500 -> First sector 17
TIC 424747720 -> First sector 13
TIC 201186294 -> First sector 18
TIC 51024887 -> First sector 18
TIC 396562848 -> First sector 18
TIC 28900646 -> First sector 19
TIC 470381900 -> First sector 19
TIC 353475866 -> First sector 19
TIC 422756130 -> First sector 18
TIC 81212286 -> First sector 20
TIC 318022259 -> First sector 20
TIC 318022259 -> First sector 20
TIC 232635922 -> First sector 14
TIC 219860288 -> First sector 15
TIC 232650365 -> First sector 14
TIC 233602827 -> First sector 14
TIC 233602827 -> First sector 14
TIC 287139872 -> First sector 14
TIC 332477926 -> First sector 14
TIC 364074068 -> First sector 17
TIC 420112587 -> First sector 14
TIC 441739871 -> First sector 14
TIC 67646988 -> First sector 21
TIC 348755728 -> First sector 8
TIC 359357695 -> First sector 11
TIC 119584412 -> First sector 22
TIC 138762614 -> First sector 22
TIC 166648874 -> First sector 22
TIC 138819293 -> First sector 22
TIC 390651552 -> First sector 23
TIC 198385543 -> First sector 17
TIC 236387002 -> First sector 24
TIC 142748283 -> First sector 14
TIC 142748283 -> First sector 14
TIC 224298134 -> First sector 15
TIC 198485881 -> First sector 14
TIC 321669174 -> First sector 14
TIC 235678745 -> First sector 14
TIC 356016119 -> First sector 14
TIC 235678745 -> First sector 14
TIC 417931300 -> First sector 14
TIC 356871098 -> First sector 14
TIC 441738827 -> First sector 15
TIC 441738827 -> First sector 15
TIC 188589164 -> First sector 24
TIC 368287008 -> First sector 24
TIC 405763009 -> First sector 14
TIC 389900760 -> First sector 18
TIC 44313455 -> First sector 26
TIC 336128819 -> First sector 26
TIC 287139872 -> First sector 14
TIC 8348911 -> First sector 24
TIC 71347873 -> First sector 20
TIC 243313296 -> First sector 14
TIC 236934937 -> First sector 15
TIC 441798995 -> First sector 14
TIC 329148988 -> First sector 16
TIC 321688498 -> First sector 17
TIC 38680052 -> First sector 1
TIC 459837008 -> First sector 19
TIC 441798995 -> First sector 14
TIC 168751223 -> First sector 4
TIC 212957629 -> First sector 3
TIC 29959760 -> First sector 4
TIC 153078576 -> First sector 3
TIC 219175972 -> First sector 1
TIC 439867639 -> First sector 4
TIC 4294779 -> First sector 6
TIC 170789802 -> First sector 5
TIC 59128183 -> First sector 5
TIC 434260570 -> First sector 5
TIC 33091590 -> First sector 7
TIC 160328683 -> First sector 6
TIC 261135533 -> First sector 15
TIC 146776480 -> First sector 8
TIC 176772671 -> First sector 8
TIC 135036669 -> First sector 9
TIC 302527524 -> First sector 9
TIC 243641947 -> First sector 11
TIC 165827520 -> First sector 11
TIC 305478010 -> First sector 15
TIC 155867025 -> First sector 19
TIC 458419328 -> First sector 20
TIC 86263325 -> First sector 22
TIC 20182780 -> First sector 23
TIC 141616639 -> First sector 19
TIC 434105094 -> First sector 2
TIC 219175972 -> First sector 1
TIC 271596225 -> First sector 1
TIC 77156829 -> First sector 4
TIC 54962195 -> First sector 9
TIC 153065527 -> First sector 3
TIC 149788158 -> First sector 8
TIC 44898913 -> First sector 4
TIC 176797879 -> First sector 4
TIC 62301521 -> First sector 13
TIC 354944123 -> First sector 13
TIC 354944123 -> First sector 13
TIC 313889049 -> First sector 2
TIC 408416746 -> First sector 8
TIC 4070275 -> First sector 5
TIC 52307802 -> First sector 1
TIC 271169413 -> First sector 11
TIC 140687214 -> First sector 1
TIC 166184428 -> First sector 11
TIC 22233480 -> First sector 40
TIC 230129753 -> First sector 14
TIC 348054109 -> First sector 26
TIC 193336820 -> First sector 14
TIC 239332587 -> First sector 15
TIC 126606859 -> First sector 15
TIC 12938488 -> First sector 41
TIC 39926974 -> First sector 42
TIC 380887434 -> First sector 42
TIC 384888319 -> First sector 42
TIC 261257684 -> First sector 12
TIC 150428135 -> First sector 1
TIC 381897917 -> First sector 13
TIC 149126400 -> First sector 1
TIC 107018378 -> First sector 10
TIC 298428237 -> First sector 14
TIC 103605399 -> First sector 14
TIC 154940895 -> First sector 19
TIC 137683938 -> First sector 14
TIC 307809773 -> First sector 43
TIC 286201103 -> First sector 15
TIC 307809773 -> First sector 43
TIC 232650365 -> First sector 14
TIC 459837008 -> First sector 19
TIC 224298134 -> First sector 15
TIC 258796169 -> First sector 17
TIC 94727308 -> First sector 43
TIC 336961891 -> First sector 42
TIC 270355392 -> First sector 4
TIC 203214081 -> First sector 44
TIC 19028197 -> First sector 44
TIC 150096001 -> First sector 43
TIC 184892124 -> First sector 44
TIC 434226736 -> First sector 44
TIC 142938659 -> First sector 4
TIC 165202476 -> First sector 31
TIC 404506270 -> First sector 4
TIC 60074373 -> First sector 7
TIC 143032776 -> First sector 36
TIC 335590096 -> First sector 10
TIC 262499797 -> First sector 3
TIC 324609476 -> First sector 27
TIC 318180448 -> First sector 13
TIC 203289099 -> First sector 44
TIC 213111428 -> First sector 12
TIC 173103335 -> First sector 45
TIC 277833995 -> First sector 8
TIC 95337971 -> First sector 45
TIC 437054764 -> First sector 44
TIC 318022259 -> First sector 20
TIC 264301607 -> First sector 14
TIC 147892178 -> First sector 14
TIC 419411415 -> First sector 15
TIC 4619242 -> First sector 42
TIC 246965431 -> First sector 18
TIC 33397739 -> First sector 42
TIC 250111245 -> First sector 42
TIC 202468443 -> First sector 15
TIC 126982221 -> First sector 42
TIC 16005254 -> First sector 43
TIC 26054627 -> First sector 42
TIC 90767677 -> First sector 18
TIC 407591297 -> First sector 21
TIC 171646471 -> First sector 22
TIC 39143128 -> First sector 22
TIC 56798909 -> First sector 44
TIC 443582629 -> First sector 9
TIC 389040826 -> First sector 8
TIC 377097547 -> First sector 45
TIC 291109653 -> First sector 23
TIC 270355392 -> First sector 4
TIC 468983280 -> First sector 7
TIC 443616612 -> First sector 9
TIC 443616612 -> First sector 9
TIC 244170332 -> First sector 3
TIC 345450130 -> First sector 5
TIC 458686847 -> First sector 34
TIC 87405719 -> First sector 45
TIC 387974148 -> First sector 43
TIC 330637910 -> First sector 44
TIC 388804061 -> First sector 45
TIC 323687123 -> First sector 44
TIC 237108775 -> First sector 14
TIC 252481136 -> First sector 21
TIC 160162137 -> First sector 14
TIC 252928337 -> First sector 20
TIC 141202786 -> First sector 22
TIC 119585136 -> First sector 22
TIC 459762279 -> First sector 20
TIC 23863105 -> First sector 16
TIC 198162530 -> First sector 14
TIC 310380289 -> First sector 16
TIC 157769780 -> First sector 14
TIC 219875976 -> First sector 14
TIC 298074836 -> First sector 14
TIC 230055368 -> First sector 22
TIC 103865797 -> First sector 25
TIC 147923561 -> First sector 14
TIC 4918918 -> First sector 21
TIC 219041246 -> First sector 16
TIC 286813592 -> First sector 22
TIC 138820713 -> First sector 22
TIC 166648874 -> First sector 22
TIC 166648874 -> First sector 22
TIC 193634953 -> First sector 25
TIC 120045750 -> First sector 14
TIC 289666986 -> First sector 19
TIC 72889156 -> First sector 25
TIC 328081248 -> First sector 54
TIC 264468702 -> First sector 18
TIC 354727907 -> First sector 14
TIC 434116397 -> First sector 56
TIC 354173595 -> First sector 42
TIC 296898634 -> First sector 15
TIC 305506996 -> First sector 55
TIC 329709756 -> First sector 15
TIC 236785891 -> First sector 14
TIC 14956304 -> First sector 14
TIC 258037656 -> First sector 55
TIC 353146308 -> First sector 55
TIC 380517859 -> First sector 15
TIC 259233660 -> First sector 14
TIC 102734241 -> First sector 14
TIC 279922257 -> First sector 18
TIC 446157122 -> First sector 19
TIC 48353358 -> First sector 14
TIC 339591840 -> First sector 53
TIC 18318288 -> First sector 25
TIC 233602827 -> First sector 14
TIC 198162530 -> First sector 14
TIC 7439480 -> First sector 11
TIC 388076422 -> First sector 16
TIC 455947620 -> First sector 16
TIC 435878153 -> First sector 17
TIC 459837008 -> First sector 19
TIC 455947620 -> First sector 16
TIC 52005579 -> First sector 42
TIC 321669174 -> First sector 14
TIC 44295981 -> First sector 56
TIC 404456775 -> First sector 56
TIC 86005116 -> First sector 55
TIC 288144647 -> First sector 57
TIC 352147273 -> First sector 17
TIC 286763141 -> First sector 9
TIC 85281192 -> First sector 17
TIC 186715217 -> First sector 18
TIC 308120029 -> First sector 18
TIC 372207328 -> First sector 16
TIC 16550540 -> First sector 60
TIC 328513434 -> First sector 19
TIC 459982699 -> First sector 14
TIC 122798633 -> First sector 7
TIC 168936945 -> First sector 7
TIC 274002141 -> First sector 19
TIC 259502942 -> First sector 19
TIC 166145361 -> First sector 11
TIC 332657786 -> First sector 8
TIC 184801054 -> First sector 34
TIC 376800517 -> First sector 10
TIC 445522339 -> First sector 7
TIC 47143972 -> First sector 8
TIC 45881495 -> First sector 9
TIC 356921678 -> First sector 9
TIC 382187347 -> First sector 1
TIC 142277868 -> First sector 10
TIC 22560356 -> First sector 10
TIC 144077896 -> First sector 10
TIC 148691985 -> First sector 38
TIC 160442729 -> First sector 11
TIC 349503728 -> First sector 12
TIC 167573692 -> First sector 1
TIC 418343229 -> First sector 19
TIC 112115898 -> First sector 7
TIC 261264800 -> First sector 1
TIC 34986694 -> First sector 9
TIC 269849065 -> First sector 1
TIC 443823169 -> First sector 7
TIC 303364023 -> First sector 9
TIC 299798795 -> First sector 1
TIC 32090583 -> First sector 1
TIC 262470965 -> First sector 67
TIC 349891396 -> First sector 13
TIC 383313006 -> First sector 13
TIC 291013124 -> First sector 27
TIC 261679541 -> First sector 1
TIC 344552721 -> First sector 13
TIC 230982415 -> First sector 2
TIC 201254754 -> First sector 1
TIC 281596890 -> First sector 2
TIC 28872266 -> First sector 42
TIC 83181153 -> First sector 43
TIC 63100069 -> First sector 71
TIC 67512645 -> First sector 22
TIC 421006834 -> First sector 7
TIC 337217173 -> First sector 4
TIC 468983280 -> First sector 7
TIC 57147191 -> First sector 44
TIC 11894726 -> First sector 22
TIC 219707850 -> First sector 14
TIC 446166017 -> First sector 22
TIC 22740615 -> First sector 22
TIC 364571121 -> First sector 15
TIC 376354189 -> First sector 18
TIC 272829240 -> First sector 17
TIC 459323923 -> First sector 25
TIC 288421619 -> First sector 82
TIC 341005781 -> First sector 15
TIC 277853911 -> First sector 15
TIC 268727719 -> First sector 17
TIC 77490011 -> First sector 18
TIC 258776466 -> First sector 14
TIC 198358065 -> First sector 14
TIC 18885659 -> First sector 80
TIC 160075684 -> First sector 14
TIC 282113152 -> First sector 55
TIC 161687285 -> First sector 15
TIC 219089784 -> First sector 15
TIC 275717567 -> First sector 15
TIC 83299322 -> First sector 14
TIC 161687211 -> First sector 15
TIC 73729607 -> First sector 58
TIC 154480367 -> First sector 16
TIC 374177909 -> First sector 16
TIC 374173310 -> First sector 16
TIC 73692250 -> First sector 18
TIC 233747840 -> First sector 14
TIC 251090642 -> First sector 21
TIC 192833836 -> First sector 5
TIC 76835246 -> First sector 92
TIC 111778581 -> First sector 2

In [ ]:
tic_id = 206609630
row = df[df["TIC ID"] == tic_id]
row

,Parameter Source Pipeline,Detection Pipeline(s),TIC ID,Full TOI ID,TOI Disposition,TIC Right Ascension,TIC Declination,TIC Right Ascension 2015.5,TIC Declination 2015.5,TMag Value,...,M_planet [ME],K_RV [m/s],TSM,ESM,Stellar Insolation [ergs/cm^2/s],Stellar Insolation [Earth Units],Sectors_Observed,Cameras,CCDs,EdgeWarn
2,spoc-s01-s69-b0A-APC,SPOC,206609630,212.01,PC,22.551,-59.5832,22.550065,-59.583245,12.186,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,"3,3,3,3,3,3,3,3,3","1,2,1,2,1,2,1,2,3","0,0,0,0,0,0,0,0,0"